#!/bin/bash
guitool=zenity

# Lock system (good one) {{{
lockfile="/tmp/.$(basename $0)-${USER}.lock"

exit_ok(){
    rm -f "$lockfile"
}
exit_error(){
    rm -f "$lockfile"
}

if [[ -r "$lockfile" ]] ; then
    PROCCESS="$(cat $lockfile)"
else
    PROCCESS=" "
fi
if (ps up $PROCCESS) 1>/dev/null 2>&1 ; then
    $guitool --error --text="$(basename $0) is already running"
    #el_error "$(basename $0) already running"
    exit 1
else
    echo $$ > "$lockfile"
fi

# traps needs to be after the lock verification, in order to not remove it when we are already running
trap "exit_ok" EXIT
trap "exit_error" 1 3 5 6 14 15 ERR TERM

# SET the lock file
echo "$$" > "$lockfile"


# end lock system }}}


# Dialog box to choose thumb's size
SIZE="$( $guitool --list --height=300 --title="Choose the thumbnail's size" --text="Select the resolution for the images to convert" --radiolist --column=$"Check" --column=$"Size" "" "Auto (for photos)" "" "Same" "" "320x240" "" "640x480" "" "800x600" "" "1024x768" "" "2048x1080" "" "4096x2160" "" "7680x4320" || echo cancel )"
[[ "$SIZE" = "cancel" ]] && exit
if [[ "$SIZE" = "" ]]; then
    $guitool --error --text="Size not defined by user. Please choose a size to use. "
    exit 1
fi

QUALITY="$( $guitool --entry --entry-text="85" --title="Quality" --text="Choose the quality value (85 for photos, 90 for screenshots)" || echo cancel )"

[[ "$QUALITY" = "cancel" ]] && exit
[[ -z "$QUALITY" ]] && QUALITY=85



# precache
PROGRESS=0
NUMBER_OF_FILES="$#"
let "INCREMENT=100/$NUMBER_OF_FILES"

( for i in "$@"
do
    echo "$PROGRESS"
    file="$i"

    # precache
    dd if="$file" of=/dev/null 2>/dev/null

    # increment progress
    let "PROGRESS+=$INCREMENT"
done
) | $guitool  --progress --title "Precaching..." --percentage=0 --auto-close --auto-kill


# Creating thumbnails. Specific work on picture should be add there as convert's option

# How many files to make the progress bar
PROGRESS=0
NUMBER_OF_FILES="$#"
let "INCREMENT=100/$NUMBER_OF_FILES"

mkdir -p "Images Resized"

( for i in "$@"
   do
       echo "$PROGRESS"
       file="$i"
       filename="${file##*/}"
       filenameraw="${filename%.*}"
       echo -e "# Converting: \t ${filename}"

       if [[ "$SIZE" = "Same" ]] ; then
	   convert -quality $QUALITY "${file}" "Images Resized/${filename%\.*}.jpg"
       else
	   if [[ "$SIZE" = "Auto (for photos)" ]] ; then
	       size_horiz="$( identify "$file" | tr ' ' '\n' | grep -E "[[:digit:]]+x[[:digit:]]+" | head -1 | sed -e 's|x.*$||g' )"
	       if [[ "$size_horiz" -lt 2400 ]] ; then
		   # no need to resize images smaller than 2400
		   convert -unsharp 5 -despeckle -quality $QUALITY "${file}" "Images Resized/${filename%\.*}.jpg"
	       else
		   # 2 / 3 of the original size
		   size_horiz_resized="$( echo "( $size_horiz / 3 ) * 2" | bc -l | sed -e 's|\.*$||g' )"
		   convert -resize ${size_horiz_resized}x${size_horiz_resized} -unsharp 5 -despeckle -quality $QUALITY "${file}" "Images Resized/${filename%\.*}.jpg"
	       fi
	   else
	       convert -resize $SIZE -quality $QUALITY "${file}" "Images Resized/${filename%\.*}.jpg"
	   fi
       fi


       let "PROGRESS+=$INCREMENT"
   done
   ) | $guitool  --progress --title "Converting Images..." --percentage=0 --auto-close --auto-kill

$guitool --info --text="Finished, you can found them in the directory 'Images Resized'"

# vim: set foldmethod=marker :
